export const REQUEST_NEW_NUMBER = 'REQUEST_NEW_NUMBER';
export const SAVE_NEW_NUMBER = 'SAVE_NEW_NUMBER';
export const ADD_ERROR_MESSAGE = 'ADD_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGES = 'CLEAR_ERROR_MESSAGES';
